// Code generated by protoc-gen-go. DO NOT EDIT.
// source: food.proto

/*
Package go_proto_food is a generated protocol buffer package.

It is generated from these files:
	food.proto

It has these top-level messages:
	Dish
	ResponseDish
*/
package go_proto_food

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dish struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,3,opt,name=price" json:"price,omitempty"`
	Quanity     int32  `protobuf:"varint,4,opt,name=quanity" json:"quanity,omitempty"`
}

func (m *Dish) Reset()                    { *m = Dish{} }
func (m *Dish) String() string            { return proto.CompactTextString(m) }
func (*Dish) ProtoMessage()               {}
func (*Dish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Dish) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Dish) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Dish) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Dish) GetQuanity() int32 {
	if m != nil {
		return m.Quanity
	}
	return 0
}

type ResponseDish struct {
	Created bool `protobuf:"varint,1,opt,name=created" json:"created,omitempty"`
}

func (m *ResponseDish) Reset()                    { *m = ResponseDish{} }
func (m *ResponseDish) String() string            { return proto.CompactTextString(m) }
func (*ResponseDish) ProtoMessage()               {}
func (*ResponseDish) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResponseDish) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func init() {
	proto.RegisterType((*Dish)(nil), "go.proto.food.Dish")
	proto.RegisterType((*ResponseDish)(nil), "go.proto.food.ResponseDish")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FoodService service

type FoodServiceClient interface {
	CreateDish(ctx context.Context, in *Dish, opts ...grpc.CallOption) (*ResponseDish, error)
}

type foodServiceClient struct {
	cc *grpc.ClientConn
}

func NewFoodServiceClient(cc *grpc.ClientConn) FoodServiceClient {
	return &foodServiceClient{cc}
}

func (c *foodServiceClient) CreateDish(ctx context.Context, in *Dish, opts ...grpc.CallOption) (*ResponseDish, error) {
	out := new(ResponseDish)
	err := grpc.Invoke(ctx, "/go.proto.food.FoodService/CreateDish", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FoodService service

type FoodServiceServer interface {
	CreateDish(context.Context, *Dish) (*ResponseDish, error)
}

func RegisterFoodServiceServer(s *grpc.Server, srv FoodServiceServer) {
	s.RegisterService(&_FoodService_serviceDesc, srv)
}

func _FoodService_CreateDish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Dish)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodServiceServer).CreateDish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.proto.food.FoodService/CreateDish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodServiceServer).CreateDish(ctx, req.(*Dish))
	}
	return interceptor(ctx, in, info, handler)
}

var _FoodService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.proto.food.FoodService",
	HandlerType: (*FoodServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDish",
			Handler:    _FoodService_CreateDish_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "food.proto",
}

func init() { proto.RegisterFile("food.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0xb1, 0x0e, 0x82, 0x30,
	0x10, 0x86, 0x05, 0x41, 0xf4, 0x50, 0x87, 0xea, 0xd0, 0xe8, 0x42, 0x98, 0x98, 0x3a, 0xe8, 0x0b,
	0x98, 0x68, 0x5c, 0x4d, 0xea, 0x13, 0x20, 0xad, 0xd2, 0x85, 0xab, 0x6d, 0x35, 0xf1, 0xed, 0x0d,
	0x25, 0x24, 0xe8, 0x76, 0xff, 0xf7, 0xe7, 0xee, 0xcb, 0x01, 0xdc, 0x11, 0x05, 0xd3, 0x06, 0x1d,
	0x92, 0xc5, 0x03, 0xbb, 0x89, 0xb5, 0x30, 0xaf, 0x21, 0x3a, 0x29, 0x5b, 0x93, 0x25, 0x84, 0x4a,
	0xd0, 0x20, 0x0b, 0x8a, 0x19, 0x0f, 0x95, 0x20, 0x19, 0xa4, 0x42, 0xda, 0xca, 0x28, 0xed, 0x14,
	0x36, 0x34, 0xf4, 0xc5, 0x10, 0x91, 0x35, 0xc4, 0xda, 0xa8, 0x4a, 0xd2, 0x71, 0x16, 0x14, 0x31,
	0xef, 0x02, 0xa1, 0x90, 0x3c, 0x5f, 0x65, 0xa3, 0xdc, 0x87, 0x46, 0x9e, 0xf7, 0x31, 0x2f, 0x60,
	0xce, 0xa5, 0xd5, 0xd8, 0x58, 0xe9, 0x8d, 0x14, 0x92, 0xca, 0xc8, 0xd2, 0xc9, 0x4e, 0x3b, 0xe5,
	0x7d, 0xdc, 0x5d, 0x20, 0x3d, 0x23, 0x8a, 0xab, 0x34, 0xef, 0xf6, 0xe4, 0x01, 0xe0, 0xe8, 0x1b,
	0xbf, 0xb6, 0x62, 0x3f, 0x0f, 0xb0, 0x16, 0x6e, 0xb6, 0x7f, 0x70, 0x28, 0xca, 0x47, 0xb7, 0x89,
	0xaf, 0xf6, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0xf0, 0xfa, 0x91, 0x08, 0x01, 0x00, 0x00,
}
